# Intrduction to NumPy


#### 1. Importer NumPy sous le nom np.

In [4]:
# your code here
import numpy as np

#### 2. Printer votre version NumPy.

In [5]:
# your code here
print(np)

<module 'numpy' from 'c:\\Users\\Utilisateur\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>


#### 3. Generer un 2x3x5 3-dimensional array avec des valeurs random. Assigner la array à la variable *a*.
**Challenge**: il y a au moins 3  façons faciles qui utilisent  numpy pour generer un random array. 

In [9]:
# Method 1
a = np.random.random((2, 3, 5))
print(a)

[[[0.90400872 0.64129008 0.46744958 0.11895746 0.2829478 ]
  [0.5930189  0.79127073 0.92268458 0.47462179 0.96732611]
  [0.4274263  0.8877803  0.79903806 0.72649689 0.32786133]]

 [[0.84768358 0.38496574 0.85596432 0.04698779 0.69321996]
  [0.36815281 0.79720826 0.39867394 0.54064583 0.284282  ]
  [0.78225243 0.7136832  0.19782284 0.80861787 0.88818854]]]


In [10]:
# Method 2
a = np.random.rand(2,3,5)
print(a)

[[[0.5982896  0.74576264 0.5170938  0.47120517 0.85800559]
  [0.67010264 0.37571403 0.27322238 0.29890187 0.5430608 ]
  [0.51568379 0.82278423 0.54692578 0.44352737 0.43640846]]

 [[0.27179299 0.28719826 0.89057667 0.07497184 0.99882592]
  [0.41527462 0.26057459 0.50499039 0.0085414  0.45777213]
  [0.63320475 0.02462272 0.82050788 0.02848087 0.9187549 ]]]


In [16]:
# Method 3
a = np.random.randint(0, 20,size=(2,3,5))
print(a)

[[[ 9 19  5 12  5]
  [ 0  0  3  1  1]
  [ 5  8 19  0 19]]

 [[ 2  7  0 12  8]
  [ 8  6 12  1 13]
  [17  5  3  3 15]]]


#### 4. Print *a*.


In [19]:
# your code here
print(a)

[[[ 9 19  5 12  5]
  [ 0  0  3  1  1]
  [ 5  8 19  0 19]]

 [[ 2  7  0 12  8]
  [ 8  6 12  1 13]
  [17  5  3  3 15]]]


#### 5. Créer un 5x2x3 3-dimensional array avec toutes les valeurs égales à 1. Assignez le array à la variable *b*.

In [ ]:
# your code here
b = np.full((5,2,3), fill_value=1)
print(b)

# b = np.ones(5,2,3)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 6. Print *b*.


In [23]:
# your code here
print(b.shape)

(5, 2, 3)


#### 7. Est ce que *a* et *b* ont la même size? Comment le prouver prove avec un code Python ?

In [24]:
# your code here
print(a.size)
print(b.size)


30
30


#### 8. Est il possible d'additionner *a* and *b*? PQ ou PQ pas?


In [26]:
# your answer here
# uniquement si les arrays sont de même forme


#### 9. Transposez *b* de telle sorte qu'il ait la même structure que *a* (i.e. devient un 2x3x5 array). Assignez le array transposé à la variable *c*.

In [27]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Essayez d'additionner *a* & *c*. Mnt ça devrait marcher. Assignez la somme (sum) à la variable *d*. Mais PQ ça marche maintenant?

In [28]:
# your code/answer here
d = a + c
print(d)


[[[10 20  6 13  6]
  [ 1  1  4  2  2]
  [ 6  9 20  1 20]]

 [[ 3  8  1 13  9]
  [ 9  7 13  2 14]
  [18  6  4  4 16]]]


#### 11. Printez *a* and *d*. Remarquez la différence et la relation entre les deux arrays en termes de valeurs? Expliquez.

In [ ]:
# your code/answer here
print(a)
print(d)
# suite à l'addition de a et c, tous les éléments de a ont été incrémenté de 1 car chaque valeur de c est égale à 1

[[[ 9 19  5 12  5]
  [ 0  0  3  1  1]
  [ 5  8 19  0 19]]

 [[ 2  7  0 12  8]
  [ 8  6 12  1 13]
  [17  5  3  3 15]]]
[[[10 20  6 13  6]
  [ 1  1  4  2  2]
  [ 6  9 20  1 20]]

 [[ 3  8  1 13  9]
  [ 9  7 13  2 14]
  [18  6  4  4 16]]]


#### 12. Multipliez *a* et *c*. Assignez le résultats à *e*.

In [31]:
# your code here
e = a * c
print(e)

[[[ 9 19  5 12  5]
  [ 0  0  3  1  1]
  [ 5  8 19  0 19]]

 [[ 2  7  0 12  8]
  [ 8  6 12  1 13]
  [17  5  3  3 15]]]


#### 13. Est ce que *e* égales à *a*? PQ ou PQ pas ?


In [ ]:
# your code/answer here
# oui car les valeurs de c sont égales à 1

#### 14. Identifiez le max, min, et la valeurs moyenne e, *d*. Assignez ces valeurs à la  variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
e_max = e.max()
e_min = e.min()
e_mean = e.mean()
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)


20
1
8.266666666666667


#### 15. Maintenant on veut labelliser les valeurs en *d*. Premièrement, créez un array vide *f* avec la même shape (i.e. 2x3x5) que *d* utilisez `np.empty`.


In [36]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[4.4e-323 9.4e-323 2.5e-323 5.9e-323 2.5e-323]
  [0.0e+000 0.0e+000 1.5e-323 4.9e-324 4.9e-324]
  [2.5e-323 4.0e-323 9.4e-323 0.0e+000 9.4e-323]]

 [[9.9e-324 3.5e-323 0.0e+000 5.9e-323 4.0e-323]
  [4.0e-323 3.0e-323 5.9e-323 4.9e-324 6.4e-323]
  [8.4e-323 2.5e-323 1.5e-323 1.5e-323 7.4e-323]]]


#### 16. Remplissez les valeurs dans *f*.

Pour chaque valeur dans *d* :  
- Si elle est supérieure à *d_min* mais inférieure à *d_mean*, attribuez 25 à la valeur correspondante dans *f*.  
- Si une valeur dans *d* est supérieure à *d_mean* mais inférieure à *d_max*, attribuez 75 à la valeur correspondante dans *f*.  
- Si une valeur est égale à *d_mean*, attribuez 50 à la valeur correspondante dans *f*.  
- Attribuez 0 à la (ou aux) valeur(s) correspondante(s) dans *f* pour *d_min* dans *d*.  
- Attribuez 100 à la (ou aux) valeur(s) correspondante(s) dans *f* pour *d_max* dans *d*.

À la fin, *f* ne doit contenir que les valeurs suivantes : 0, 25, 50, 75 et 100.

**Remarque** : vous n’êtes pas obligé d’utiliser Numpy pour cette question.


In [38]:
# your code here
conditions = [
    (d>d_min) & (d<d_mean),
    (d>d_mean) & (d<d_max),
    (d==d_mean),
    (d==d_min),
    (d==d_max)]

valeurs = [25, 75, 50, 0, 100]

f = np.select(conditions, valeurs, default=d)

# d = np.random.randint(0, 7, size=(2, 3, 5))

# # Conditions
# conditions = [
#     (d > 1) & (d < 3),     # si 1 < d < 3 ➜ 10
#     (d > 4) & (d < 6)      # si 4 < d < 6 ➜ 20
# ]

# # Valeurs à attribuer selon la condition
# valeurs = [
#     10,  # pour la 1ère condition
#     20   # pour la 2ème condition
# ]

# # Appliquer les transformations
# f = np.select(conditions, valeurs, default=d)  # sinon on garde la valeur d'origine

print(f)

[[[ 75 100  25  75  25]
  [  0   0  25  25  25]
  [ 25  75 100   0 100]]

 [[ 25  25   0  75  75]
  [ 75  25  75  25  75]
  [ 75  25  25  25  75]]]


#### 17. Printez *d* et *f*. Avez vous obtenu ce que vous expectiez expected *f*?
Par exemple, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Question bonus : au lieu d’utiliser des nombres (c’est-à-dire 0, 25, 50, 75 et 100), utilisez des valeurs sous forme de chaînes de caractères ("A", "B", "C", "D" et "E") pour étiqueter les éléments du tableau. Pour l’exemple ci-dessus, le résultat attendu est :


```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here